image: hmctspublic.azurecr.io/k8s-env-injector:db4758
replicas: 2
environment:
  CLUSTER_NAME: aks-test-01
dnsOptions:
  ndots: 3
#  single-request-reopen:
#  use-vc:
nodeAffinityTerms: {}
#  - matchExpressions:
#      - key: agentpool
#        operator: In
#        values:
#          - ubuntu18
#          - ubuntu1804